type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

input NewTodo {
  text: String!
  userId: String!
}

extend type Query {
  todos: [Todo!]!
}

extend type Mutation {
  createTodo(input: NewTodo!): Todo!
}